name: homework_1
on: [push]
jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make

