name: homework1
on: 
  push:
#    branches:
#      - main
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#        with:
#          submodules: true
      - run: sudo apt-get update && sudo apt-get install cmake libboost-test-dev -y
      - run: cmake ./src -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
#      - run: cmake --build . --target package

